""" User-configured values """

from user_settings.new_config import load_config

CONFIG = load_config()
PATH = CONFIG['PATH']
PREFIX = CONFIG['PREFIX']
REINDEX = CONFIG['REINDEX']
FIRST_RESIDUE = CONFIG['FIRST_RESIDUE']
BUILD_MSA = CONFIG['BUILD_MSA']
RUN_AF2 = CONFIG['RUN_AF2']
OPTIMIZE_PARAMETERS = CONFIG['OPTIMIZE_PARAMETERS']
JACKHMMER_PATH = ''
COLABFOLDBATCH_PATH = ''