""" User-configured values """

PREDICTION_ROOT = "."
REINDEX = False,
FIRST_RESIDUE = 0
BUILD_MSA = False
RUN_AF2 = False
OPTIMIZE_PARAMETERS = True
TEST_MUTANTS = True
JACKHMMER_PATH = ''
COLABFOLDBATCH_PATH = ''
MSA_PATHS = ''

