""" User-configured values """



SYSTEM_NAME = 'abl_wt'
p
PREDICTION_ROOT = "."
FIRST_RESIDUE = 0
REINDEX = False,
BUILD_MSA = False
RUN_AF2 = False
OPTIMIZE_PARAMETERS = True
TEST_MUTANTS = True
JACKHMMER_PATH = ''
COLABFOLDBATCH_PATH = ''
MSA_PATHS = ''

